# Generated by the Protocol Buffers compiler. DO NOT EDIT!
# source: whatsapp.proto
# plugin: grpclib.plugin.main
import abc
import typing

import grpclib.const
import grpclib.client
if typing.TYPE_CHECKING:
    import grpclib.server

import whatsapp_pb2


class WhatsAppServiceBase(abc.ABC):

    @abc.abstractmethod
    async def CreateThread(self, stream: 'grpclib.server.Stream[whatsapp_pb2.CreateThreadRequest, whatsapp_pb2.CreateThreadResponse]') -> None:
        pass

    @abc.abstractmethod
    async def CreateThreadAnalizer(self, stream: 'grpclib.server.Stream[whatsapp_pb2.CreateThreadAnalizerRequest, whatsapp_pb2.CreateThreadAnalizerResponse]') -> None:
        pass

    @abc.abstractmethod
    async def GenerateResponse(self, stream: 'grpclib.server.Stream[whatsapp_pb2.GenerateResponseRequest, whatsapp_pb2.GenerateResponseResponse]') -> None:
        pass

    @abc.abstractmethod
    async def GenerateResponseAnalizer(self, stream: 'grpclib.server.Stream[whatsapp_pb2.GenerateResponseAnalizerRequest, whatsapp_pb2.GenerateResponseAnalizerResponse]') -> None:
        pass

    def __mapping__(self) -> typing.Dict[str, grpclib.const.Handler]:
        return {
            '/whatsapp.WhatsAppService/CreateThread': grpclib.const.Handler(
                self.CreateThread,
                grpclib.const.Cardinality.UNARY_UNARY,
                whatsapp_pb2.CreateThreadRequest,
                whatsapp_pb2.CreateThreadResponse,
            ),
            '/whatsapp.WhatsAppService/CreateThreadAnalizer': grpclib.const.Handler(
                self.CreateThreadAnalizer,
                grpclib.const.Cardinality.UNARY_UNARY,
                whatsapp_pb2.CreateThreadAnalizerRequest,
                whatsapp_pb2.CreateThreadAnalizerResponse,
            ),
            '/whatsapp.WhatsAppService/GenerateResponse': grpclib.const.Handler(
                self.GenerateResponse,
                grpclib.const.Cardinality.UNARY_UNARY,
                whatsapp_pb2.GenerateResponseRequest,
                whatsapp_pb2.GenerateResponseResponse,
            ),
            '/whatsapp.WhatsAppService/GenerateResponseAnalizer': grpclib.const.Handler(
                self.GenerateResponseAnalizer,
                grpclib.const.Cardinality.UNARY_UNARY,
                whatsapp_pb2.GenerateResponseAnalizerRequest,
                whatsapp_pb2.GenerateResponseAnalizerResponse,
            ),
        }


class WhatsAppServiceStub:

    def __init__(self, channel: grpclib.client.Channel) -> None:
        self.CreateThread = grpclib.client.UnaryUnaryMethod(
            channel,
            '/whatsapp.WhatsAppService/CreateThread',
            whatsapp_pb2.CreateThreadRequest,
            whatsapp_pb2.CreateThreadResponse,
        )
        self.CreateThreadAnalizer = grpclib.client.UnaryUnaryMethod(
            channel,
            '/whatsapp.WhatsAppService/CreateThreadAnalizer',
            whatsapp_pb2.CreateThreadAnalizerRequest,
            whatsapp_pb2.CreateThreadAnalizerResponse,
        )
        self.GenerateResponse = grpclib.client.UnaryUnaryMethod(
            channel,
            '/whatsapp.WhatsAppService/GenerateResponse',
            whatsapp_pb2.GenerateResponseRequest,
            whatsapp_pb2.GenerateResponseResponse,
        )
        self.GenerateResponseAnalizer = grpclib.client.UnaryUnaryMethod(
            channel,
            '/whatsapp.WhatsAppService/GenerateResponseAnalizer',
            whatsapp_pb2.GenerateResponseAnalizerRequest,
            whatsapp_pb2.GenerateResponseAnalizerResponse,
        )
