# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: whatsapp.proto
# Protobuf Python Version: 5.27.0-rc3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    0,
    '-rc3',
    'whatsapp.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0ewhatsapp.proto\x12\x08whatsapp\"\x15\n\x13\x43reateThreadRequest\")\n\x14\x43reateThreadResponse\x12\x11\n\tthread_id\x18\x01 \x01(\t\"\x1d\n\x1b\x43reateThreadAnalizerRequest\":\n\x1c\x43reateThreadAnalizerResponse\x12\x1a\n\x12thread_id_analizer\x18\x01 \x01(\t\"Q\n\x17GenerateResponseRequest\x12\r\n\x05phone\x18\x01 \x01(\t\x12\x11\n\tthread_id\x18\x02 \x01(\t\x12\x14\n\x0cmessage_body\x18\x03 \x01(\t\",\n\x18GenerateResponseResponse\x12\x10\n\x08response\x18\x01 \x01(\t\"S\n\x1fGenerateResponseAnalizerRequest\x12\x1a\n\x12thread_id_analizer\x18\x01 \x01(\t\x12\x14\n\x0cmessage_body\x18\x02 \x01(\t\"4\n GenerateResponseAnalizerResponse\x12\x10\n\x08response\x18\x01 \x01(\t2\x95\x03\n\x0fWhatsAppService\x12M\n\x0c\x43reateThread\x12\x1d.whatsapp.CreateThreadRequest\x1a\x1e.whatsapp.CreateThreadResponse\x12\x65\n\x14\x43reateThreadAnalizer\x12%.whatsapp.CreateThreadAnalizerRequest\x1a&.whatsapp.CreateThreadAnalizerResponse\x12Y\n\x10GenerateResponse\x12!.whatsapp.GenerateResponseRequest\x1a\".whatsapp.GenerateResponseResponse\x12q\n\x18GenerateResponseAnalizer\x12).whatsapp.GenerateResponseAnalizerRequest\x1a*.whatsapp.GenerateResponseAnalizerResponseB\x15Z\x13\x63hatbot/utils/protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'whatsapp_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\023chatbot/utils/proto'
  _globals['_CREATETHREADREQUEST']._serialized_start=28
  _globals['_CREATETHREADREQUEST']._serialized_end=49
  _globals['_CREATETHREADRESPONSE']._serialized_start=51
  _globals['_CREATETHREADRESPONSE']._serialized_end=92
  _globals['_CREATETHREADANALIZERREQUEST']._serialized_start=94
  _globals['_CREATETHREADANALIZERREQUEST']._serialized_end=123
  _globals['_CREATETHREADANALIZERRESPONSE']._serialized_start=125
  _globals['_CREATETHREADANALIZERRESPONSE']._serialized_end=183
  _globals['_GENERATERESPONSEREQUEST']._serialized_start=185
  _globals['_GENERATERESPONSEREQUEST']._serialized_end=266
  _globals['_GENERATERESPONSERESPONSE']._serialized_start=268
  _globals['_GENERATERESPONSERESPONSE']._serialized_end=312
  _globals['_GENERATERESPONSEANALIZERREQUEST']._serialized_start=314
  _globals['_GENERATERESPONSEANALIZERREQUEST']._serialized_end=397
  _globals['_GENERATERESPONSEANALIZERRESPONSE']._serialized_start=399
  _globals['_GENERATERESPONSEANALIZERRESPONSE']._serialized_end=451
  _globals['_WHATSAPPSERVICE']._serialized_start=454
  _globals['_WHATSAPPSERVICE']._serialized_end=859
# @@protoc_insertion_point(module_scope)
